# Generated by Django 4.1.7 on 2023-05-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "male"), ("f", "female")], max_length=1
                    ),
                ),
                ("weight", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                ("date_in", models.DateField()),
                ("date_out", models.DateField()),
                ("address_found", models.CharField(max_length=100)),
                ("box", models.CharField(max_length=50)),
                ("group_name", models.CharField(max_length=50)),
                ("group_link", models.URLField()),
                ("link", models.URLField()),
            ],
        ),
    ]
