# Generated by Django 4.1.7 on 2023-05-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webscraper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebscrappingProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.IntegerField()),
                ("working", models.BooleanField()),
            ],
        ),
    ]
