name: Deploy to server

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/private.key
        sudo chmod 600 ~/.ssh/private.key
        ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: Connect and deploy
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} -i ~/.ssh/private.key "cd PieskiUW/scripts; ./production.sh; exit"
    - name: cleanup
      run: rm -rf ~/.ssh