name: Lint python code
on: [push]
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install -r requirements.txt
      - run: pylint --rcfile .pylint/.pylintrc $(git ls-files '*.py')

  blackstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install -r requirements.txt
      - run: black --check $(git ls-files '*.py')